### ISSUE TITLE
Publishing fails, claims dependency has invalid name

### ISSUE THREAD

**Issue by sqrrrl** [GoogleCloudPlatform/wombat-dressing-room#259]
Trying to release https://github.com/google/clasp, failing due to very unexpected error about a nested dependency

From log:

```
npm error code E404
npm error 404 Not Found - GET https://wombat-dressing-room.appspot.com/yoctocolors-cjs/-/yoctocolors-cjs-2.1.2.tgz
npm error 404
npm error 404  'https://registry.npmjs.org/yoctocolors-cjs/-/yoctocolors-cjs-2.1.2.tgz' is not in this registry.
npm error 404 This package name is not valid, because 
npm error 404  1. name can only contain URL-friendly characters
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
```

The original npmjs.org URL *is* valid, but not when proxied through wombat-dressing-room. Seems like some overly strict validation in WDR?

**Comment by sqrrrl** [comment]
Error is from npm publish, workflow is:

```
on:
  release:
    types: [created]
name: release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 22
          registry-url: 'https://wombat-dressing-room.appspot.com'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.WOMBAT_DRESSING_ROOM_TOKEN}}
```

Was working 2 months ago. Things that changed are:

* Dependencies of project updated
* Workflow updated to node-version 22
